const usStates = [
  { key: 1, value: 'Alabama' },
  { key: 2, value: 'Alaska' },
  { key: 3, value: 'Arizona' },
  { key: 4, value: 'Arkansas' },
  { key: 5, value: 'California' },
  { key: 6, value: 'Colorado' },
  { key: 7, value: 'Connecticut' },
  { key: 8, value: 'Delaware' },
  { key: 9, value: 'Florida' },
  { key: 10, value: 'Georgia' },
  { key: 11, value: 'Hawaii' },
  { key: 12, value: 'Idaho' },
  { key: 13, value: 'Illinois' },
  { key: 14, value: 'Indiana' },
  { key: 15, value: 'Iowa' },
  { key: 16, value: 'Kansas' },
  { key: 17, value: 'Kentucky' },
  { key: 18, value: 'Louisiana' },
  { key: 19, value: 'Maine' },
  { key: 20, value: 'Maryland' },
  { key: 21, value: 'Massachusetts' },
  { key: 22, value: 'Michigan' },
  { key: 23, value: 'Minnesota' },
  { key: 24, value: 'Mississippi' },
  { key: 25, value: 'Missouri' },
  { key: 26, value: 'Montana' },
  { key: 27, value: 'Nebraska' },
  { key: 28, value: 'Nevada' },
  { key: 29, value: 'New Hampshire' },
  { key: 30, value: 'New Jersey' },
  { key: 31, value: 'New Mexico' },
  { key: 32, value: 'New York' },
  { key: 33, value: 'North Carolina' },
  { key: 34, value: 'North Dakota' },
  { key: 35, value: 'Ohio' },
  { key: 36, value: 'Oklahoma' },
  { key: 37, value: 'Oregon' },
  { key: 38, value: 'Pennsylvania' },
  { key: 39, value: 'Rhode Island' },
  { key: 40, value: 'South Carolina' },
  { key: 41, value: 'South Dakota' },
  { key: 42, value: 'Tennessee' },
  { key: 43, value: 'Texas' },
  { key: 44, value: 'Utah' },
  { key: 45, value: 'Vermont' },
  { key: 46, value: 'Virginia' },
  { key: 47, value: 'Washington' },
  { key: 48, value: 'West Virginia' },
  { key: 49, value: 'Wisconsin' },
  { key: 50, value: 'Wyoming' }
];

export default usStates;
